name: .NET

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]
  workflow_dispatch:

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2
    - name: Setup .NET
      uses: actions/setup-dotnet@v1
      with:
        dotnet-version: 5.0.x
    - name: Restore dependencies
      run: dotnet restore SharpCaster.sln
    - name: Get the version
      id: get_version
      run: echo ::set-output name=VERSION::${GITHUB_REF#refs/tags/}
    - name: Build
      run: dotnet build --no-restore --configuration Release /p:Version=${{ steps.get_version.outputs.VERSION }} SharpCaster.sln
    - name: Package
      run: dotnet pack --configuration Release /p:Version=${{ steps.get_version.outputs.VERSION }} Sharpcaster/Sharpcaster.csproj
    - name: Push
      if: github.ref == 'refs/heads/main'
      run:  dotnet nuget push "**/*.nupkg" -k $NUGET_AUTH_TOKEN -s nuget.org
      env:
        NUGET_AUTH_TOKEN: ${{ secrets.NUGET }}
